### ISSUE TITLE
Update to MC 1.20*

### ISSUE THREAD

**Issue by xtexx** [davidmayr/AudioShutdown#2]
Please update this mod for Minecraft 1.20{,.1}

Thanks a lot

**Comment by davidmayr** [comment]
Does it not work on 1.20? Can you send me the crash log?

**Comment by xtexx** [comment]
https://github.com/MenschenToaster/AudioShutdown/blob/main/src/main/resources/fabric.mod.json#L26

The depends is 1.19.3, and fabric-loader will reject loading such a mod.

**Comment by venaminecraft** [comment]
Any update on this? Would be great to have the mod for 1.20.2.

**Comment by davidmayr** [comment]
Working on it ^^

**Comment by davidmayr** [comment]
This is implemented now. Version 2 also brings the new Audio Pause feature, which has pretty much the same effect with even better performance. We also always shutdown the engine now if your master volume is 0.

Hope this helps! https://modrinth.com/mod/audioshutdown/version/2.0

**Comment by venaminecraft** [comment]
Thanks a lot for that fast update 🥳

**Comment by xtexx** [comment]
Thanks a lot!
