### ISSUE TITLE
[Friendly Reminder] 1.21.X (1.21.1 Especially) Update

### ISSUE THREAD

**Issue by SussyBob** [davidmayr/AudioShutdown#7]
Is this mod still being maintained, or has it been discontinued? It's been very helpful to me ❤️.

**Comment by davidmayr** [comment]
Is it not working on the newest version?

**Comment by davidmayr** [comment]
![grafik](https://github.com/user-attachments/assets/a3b26ee5-b9da-431b-a06f-f93a0f5ba740)
I haven't confirmed if it works, but it sure does load

**Comment by SussyBob** [comment]
sorry man, its working. it was crashing because i use the old quilt loaders, thanks for your respond.
